### ISSUE TITLE
Food Security with Groups harvester update

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#103]
### Please describe the expected behaviour
Since the Food Security harvester (without groups implemented) has been on the production portal and it has collected some data, we need to be able to update the datasets that were previously harvested.
It would be nice to have an `update` option in the configuration file available, so we can go and update the datasets that were already created

### Please describe the actual behaviour
The food Security harvesters we only have the following options:
```
{
"start_date":"2017-01-01",
"collection":"FAPAR",
"username":"nextgeoss",
"password":"nextgeoss",
}
```
If we create a new Food Security harvester and we try to harvest from 01-01-2017 (already harvested datasets) the harvester will ignore them.

### What steps can be taken to reproduce the issue?
Create a new food security harvester and try to harvest what has already been harvested before.

**Comment by davidcordeiro-deimos** [comment]
Hi @georgiana-b does your docker setup have a problem with # in the middle of the branch name? Just because PR #98 was merged successfully. 

If indeed, it does have a problem, please let me know, and I will do the same with this PR.

**Comment by JGulic** [comment]
merged on master. closing
