### ISSUE TITLE
Sentinel harvesters: Issues with the harvesting URL

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#106]
### Please describe the expected behaviour
We were running the Sentinel harvester with the following configurations:
````
{
  "source": "esa_scihub",
  "update_all": false,
  "start_date": "2018-01-16T10:30:00.000Z",
  "datasets_per_job": 100,
  "timeout": 60,
  "skip_raw": true,
  "make_private": false
}
````
When we set up a configuration, only with a start_date we are expecting that the harvester will run form that day till now, and collect everything in that time range.

````
{
  "source": "esa_scihub",
  "update_all": false,
  "start_date": "2018-01-16T10:30:00.000Z",
  "end_date": "2018-01-16T11:00:00.000Z",
  "datasets_per_job":  99,
  "timeout": 4,
  "skip_raw": true,
  "make_private": false
}
````
When we set up a configuration, with a start_date and end_date we are expecting that the harvester will run and collect everything in that time range.

1. From the logs we can see that the restart date is set but then it's never used.

2. The start_date is always set to the start date that we have in the configuration file, and the URL is constructed with the start_date (ignoring the restart date)

3. The URL always starts with start index 0 and this index never gets updated in the next runs. This means that the harvester only calls the URL with start index 0 in the first run. Then on the second run, the start index is not updated and the harvester again collects the same datasets and the result is: 0 datasets added.
The harvester tells us that there are no datasets to collect, and in fact there are:

![Screenshot from 2019-10-22 11-08-49](https://user-images.githubusercontent.com/850400/67272183-5c3c5e80-f4bc-11e9-9e75-2f9399fe9f6c.png)

The harvester never goes to the next url (take a look at the screenshot).

These are some logs from investigating this issue:
````
SELECT harvest_object.id AS harvest_object_id, harvest_object.guid AS harvest_object_guid, harvest_object.current AS harvest_object_current, harvest_object.gathered AS harvest_object_gathered, harvest_object.fetch_started AS harvest_object_fetch_started, harvest_object.content AS harvest_object_content, harvest_object.fetch_finished AS harvest_object_fetch_finished, harvest_object.import_started AS harvest_object_import_started, harvest_object.import_finished AS harvest_object_import_finished, harvest_object.state AS harvest_object_state, harvest_object.metadata_modified_date AS harvest_object_metadata_modified_date, harvest_object.retry_times AS harvest_object_retry_times, harvest_object.harvest_job_id AS harvest_object_harvest_job_id, harvest_object.harvest_source_id AS harvest_object_harvest_source_id, harvest_object.package_id AS harvest_object_package_id, harvest_object.report_status AS harvest_object_report_status 
FROM harvest_object 
WHERE harvest_object.harvest_source_id = %(harvest_source_id_1)s AND harvest_object.import_finished IS NOT NULL ORDER BY harvest_object.import_finished DESC 
 LIMIT %(param_1)s
> /home/gulic/ckan/lib/nextgeoss/src/ckanext-nextgeossharvest/ckanext/nextgeossharvest/harvesters/esa.py(106)gather_stage()
-> log.debug('Restart date is {}'.format(restart_date))
(Pdb) print restart_date
2018-01-16T10:37:30.278Z
(Pdb) continue
2019-10-22 10:55:56,506 DEBUG [ckanext.nextgeossharvest.harvesters.esa.ESASentinel.gather] Restart date is 2018-01-16T10:37:30.278Z
START DATE: 2018-01-16T10:30:00.000Z
2019-10-22 10:55:56,507 DEBUG [ckanext.nextgeossharvest.harvesters.esa.ESASentinel.gather] Harvest URL is https://scihub.copernicus.eu/dhus/search?q=ingestiondate:[2018-01-16T10:30:00.000Z TO NOW] AND NOT producttype:RAW&orderby=ingestiondate asc&start=0&rows=100
https://scihub.copernicus.eu/dhus/search?q=ingestiondate:[2018-01-16T10:30:00.000Z TO NOW] AND NOT producttype:RAW&orderby=ingestiondate asc&start=0&rows=100
/usr/lib/ckan/nextgeoss/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
INFO | esa_scihub   | 2019-10-22 08:55:56.507294 | 200 | 2.278984s
2019-10-22 10:55:58,848 INFO  [provider_logger] esa_scihub   | 2019-10-22 08:55:56.507294 | 200 | 2.278984s
2019-10-22 10:55:59,744 DEBUG [ckanext.nextgeossharvest.lib.opensearch_base] s1b_wv_slc__1ssv_20180115t214315_20180115t215151_009187_010742_2864 will not be updated.
````

### Please describe the actual behaviour
The harvester should collect all the datasets in a given time range.

### What steps can be taken to reproduce the issue?
Create a Sentinel harvester and then add some of the configuration mentioned in the previous section, or use your own. And run the harvester.

**Comment by michellecbox** [comment]
following

**Comment by davidcordeiro-deimos** [comment]
I created the PR #109 with the fix for this issue

**Comment by JGulic** [comment]
Take a look at my comment on the PR

**Comment by JGulic** [comment]
@davidcordeiro-deimos Please make sure that you are testing your code before submitting a PR.

**Comment by davidcordeiro-deimos** [comment]
The error has been corrected. 

Due to the fact that I am not able to run the master branch on my development environment, nor any other branch derived directly from master, I have to develop in an older branch, and then transfer the changes to the new branch.

However, this mishap was my fault, and it will not happen again.

**Comment by davidcordeiro-deimos** [comment]
@georgiana-b similarly to Issue #105 I also created a new PR #111 with branch name without the special characters

**Comment by JGulic** [comment]
closing
