### ISSUE TITLE
ProbaV datasets are missing StartTime and StopTime

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/ckanext-nextgeossharvest#116]
All datasets have both `StartTime` - `StopTime` and `timerange_start` - `timerange_end` but  
ProbaV datasets lack the `StartTime` and `StopTime` fields.
For an example see https://catalogue.nextgeoss.eu/api/action/package_show?id=probav_s1_toa_x35y12_20181008_1km_v101

Is there a reason for it or was it just a small mistake?

**Comment by joaandrade** [comment]
Issue solved in the pull request:
https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/119

**Comment by JGulic** [comment]
Since we have decided that we are going to use timerange_start and timerange_end the PR #119 has not been merged.
I am closing this ticket since it's not relevant
