### ISSUE TITLE
Static EBV datasets are lacking timerange_start & timerange_end

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/ckanext-nextgeossharvest#117]
All datasets have both `StartTime` - `StopTime` and `timerange_start` - `timerange_end` but those created with the [Static EBV harvester](https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/75/commits/e8fb6f740540b16deddb8eba7feb8e11db12b829) lack the `timerange_start` and `timerange_end` fields.
For an example, see https://catalogue.nextgeoss.eu/api/action/package_show?id=floodmapgl_rp10y

Is there a reason for it or was it just a small mistake?

**Comment by georgiana-b** [comment]
While we're on the topic, could we remove the `dataset_extras` field from their extras as well? It appears to be reluctant.

**Comment by joaandrade** [comment]
Issue solved with the pull request https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/120
