### ISSUE TITLE
Deimos-2 - check why some fields are not being collected

### ISSUE THREAD

**Issue by joaandrade** [NextGeoss/ckanext-nextgeossharvest#145]
### Please describe the expected behaviour
The followin fields should be collected since they are considered in the harvester code:
- ASCID
- CloudCoverage
- Roll
- Pitch
- Yaw

However, they are not being collected.

### Please describe the actual behaviour
These fields should be collected.

### What steps can be taken to reproduce the issue?
Run Deimos-2 harvester

**Comment by JGulic** [comment]
Resolved with PR #166
