### ISSUE TITLE
Plan4All harvester: Doesn't have start and end date in the configuration

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#148]
For all the harvesters we have the option to set a start and an end date.
Plan4All doesn't allow this option in the configuration file. It would be good if we are able to set the options in case we need to harvest more recent datasets, and at the same time have a harvester that runs from further back.

Also it is unclear to me which date do we use as a start date for this harvester.

**Comment by davidcordeiro-deimos** [comment]
From our discussion with the data provider at the time, our conclusions were as follow:
- Not possible to sort by update time / ingestion time, only by title
- Number of products is near static
