### ISSUE TITLE
Update ReadMe for Food Security with Groups

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#164]
The Readme file is missing the configuration for groups.
We've added this functionality in order to associate Datasets with Topics during dataset creation

**Comment by georgiana-b** [comment]
As described in the PR where the functionality was added:

https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/104

**Comment by davidcordeiro-deimos** [comment]
Done.
Check https://github.com/NextGeoss/ckanext-nextgeossharvest/wiki/13.-Harvesting-Food-Security-pilot-outputs
