### ISSUE TITLE
Simocean harvester: Remove fields from the extras (do not save in the database) & reindex for older datasets

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#171]
1. Remove the following fields from the index:

- Limitations On Public Access
- CreationTime
- Responsible Party
- Metadata Date
- StartTime
- StopTime

2. Make sure that we are not indexing the fields mentioned above, when we are reindexing old datasets

**Comment by davidcordeiro-deimos** [comment]
This issue cannot be resolved at the moment, due to the fact that I require access to the SIMOcean catalog / metadata to test the changes, and the catalog is currently down.

As soon as the catalog is back up, I will resume this task.

**Comment by JGulic** [comment]
Addressed with PR #199
