### ISSUE TITLE
CMEMS dataset names are incorrect

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#22]
According to the cmems_base.py, the dataset names should have the form `'SST-GLO-L4-DAILY-NRT-OBS-010-001-' + year + month + day`, `'ARCTIC-' + fyear + fmonth + fday + '-FORECAST-PHYS-002-001-' + year + month + day`, etc. depending on the collection they belong to.

However, those names are not used when creating the datasets. Instead, they're assigned to an `extra` called `datasetname`. The `name` is created by CKAN converting the `title` of the dataset according to the default behavior when no `name` is set. For example, the names are `global-observed-sea-surface-temperature`, `global-observed-sea-surface-temperature1`, `global-observed-sea-surface-temperature2`, etc. if the `title` is `Global Observed Sea Surface Temperature`.

**Comment by joaandrade** [comment]
This issue were corrected in the commit 7980b34

**Comment by kmbn** [comment]
Looks good.
