### ISSUE TITLE
Do CMEMS datasets require thumbnails?

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#27]
In `_get_metadata_create_objects()`, which is called during the gather stage, a harvest object is only created if requesting the thumbnail returns 200 and the resulting metadata dictionary will always have a thumbnail key-value pair.

In `_create_package_dict()`, which is called during the import stage, the try-except block below checks if the thumbnail key-value pair exists in a roundabout fashion.

What is the case: that CMEMS datasets _don't_ require thumbnails (in which case `_get_metadata_create_objects()` needs to be updated) or that CMEMS datasets _do_ require thumbnails (in which case the try-except block should be removed)?
``
try:
    thumbnail= metadata['thumbnail']
    extras_dict = self._generateExtrasDict(name=dataset_name.upper(),metadata=metadata,thumbnail=thumbnail, spatial=spatial_json)
except Exception:
    extras_dict = self._generateExtrasDict(name=dataset_name.upper(),metadata=metadata,spatial=spatial_json)
```

**Comment by joaandrade** [comment]
The CMEMS services includes WMS (GetMap), that we are using to get thumbnails and also to check if the product exists for a certain day, and also the ftp where the netCDF files are stored. If for a day, the wms service retrieves an image (map), then the netCDF will also exist in the ftp. If we don't want to catalogue thumbnails for a specific collection of CMEMS data, we can still use the WMS to check if the netCDF files exist or not

**Comment by kmbn** [comment]
OK, then there's no need to check for a thumbnail or pass it as a separate kwarg, because every dataset will have a thumbnail.

**Comment by joaandrade** [comment]
Yes, all the datasets will have a thumbnail. But we have to check if the dataset exists. We can use the WMS service (thumbnail) or request the FTP URL. It is important to check at least one of them. We followed the WMS option.

**Comment by kmbn** [comment]
I understand. My comment wasn't clearly written—when I said there's no need to check for a thumbnail, I meant that there's no need to check for e.g., `metadata['thumbnail]` because every dataset will have a thumbnail. We remove the unnecessary code.

**Comment by kmbn** [comment]
The unnecessary code was removed in commit c75f8e3bbd984fa732d0e8b1ff861e878630667f.
