### ISSUE TITLE
CMEMSHarvester inherits from SpatialHarvester but doesn't use any of its methods or attributes

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#32]

**Comment by davv-deimos** [comment]
resolved in commit [7b9e1bd](https://github.com/NextGeoss/ckanext-nextgeossharvest/commit/7b9e1bddf72929c73b33cdca72e418be01ce452a)

**Comment by kmbn** [comment]
Looks good.
