### ISSUE TITLE
Lines 468–494 in _get_package_dict() have no effect on the package dict

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#33]
Lines 468–494 in _get_package_dict() in cmems_base.py create an `extras` variable and then use it to create an `extras_as_dict` variable, but `extras_as_dict` is never added to the `package_dict` that the method returns nor does it have an effect on the content of the `package_dict`.

That section of code also contains a conditional block that depends on config values that are never set. It will never be executed.

**Comment by joaandrade** [comment]
This piece of code was removed in the commit [dd7b8a6](https://github.com/NextGeoss/ckanext-nextgeossharvest/commit/dd7b8a62588a9a929cc8f4f1f720d601bd81becd#diff-c207c016ab562353bd6ac84e9c559792)

**Comment by kmbn** [comment]
Looks good.
