### ISSUE TITLE
CMEMS: Tag-creation conditional statements are never executed

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#34]
See lines 438–449 of cmems_base.py in the `_get_package_dict()` method.

`iso_values` is created from `metadata` but it is not necessary: neither `iso_values` nor `metadata` are modified, so there's no reason to create and use `iso_values` instead of just using `metadata`.

The tags for the dataset are passed to the method as a separate variable (`tags_dict`). `metadata`/`iso_values` never contains `tags`, so there's no reason to check for it. `default_tags` is not part of the config, so there's no reason to check for it.

**Comment by joaandrade** [comment]
This piece of code was removed in the commit [d4e4940](https://github.com/NextGeoss/ckanext-nextgeossharvest/commit/d4e49408dac4a48962b9a400f55bbfd5281402a3#diff-c207c016ab562353bd6ac84e9c559792)

**Comment by kmbn** [comment]
Looks good.
