### ISSUE TITLE
[CMEMS Branch] FTP request inefficiency 

### ISSUE THREAD

**Issue by davv-deimos** [NextGeoss/ckanext-nextgeossharvest#36]
The current implementation was written by reusing the code that performed HTTP requests. This makes the code inefficient. Only one session per Harvester/Product Type should be opened and the whole directory checked for new products. For example, now the forecast product makes 10 requests, for each day, but a single one would be necessary, since the content of a ftp list request in a unix ls command with a list of all the available products.

**Comment by joaandrade** [comment]
The FTP requests are now following a different logic for all the collections. There are no ftp requests to individual files. As @davv-deimos suggested, with a single request, it is now possible to get the content of a ftp list and, at the same time, all the products available. The FTP folders are splitted by year/month.

**Comment by kmbn** [comment]
Thank you!
