### ISSUE TITLE
[Sentinel] Missing microseconds in DHuS results will cause crashes

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#43]
The DHuS results are not always as well-formed as we hoped.

See https://sentinels.space.noa.gr/dhus/search?q=ingestiondate:[2018-04-01T00:00:00.000Z%20TO%202018-04-02T00:00:00.000Z]&orderby=ingestiondate%20asc&start=0&rows=100 for an example.

Entry S3A_SR_1_SRA____20180331T220405_20180331T225435_20180401T160650_3029_029_286______LN3_O_ST_003 has `<date name="ingestiondate">2018-04-01T16:54:38Z</date>`, which is missing the microseconds.

It seems like DHuS truncates the microseconds. Usually they're three digits, sometimes they're two digits—in this case the timestamp was probably .000Z and they were cut off entirely.

As long as there is some value in the microseconds position, our parser doesn't mind. But if there's nothing in the microseconds position, the parser will crash.

**Comment by joaandrade** [comment]
Probably we have to catch the exception and in these cases add manually the 000, no?

**Comment by kmbn** [comment]
I just ran into the issue today by chance while running a test. We've harvested thousands of products in the past without running into a similar issue, so it seem like a rare occurance that could hit any of the DHuS instances. (How often are the microseconds exactly 000?)

Yes, we'll have to catch the exception or parse the dates differently, and then add microseconds.

**Comment by kmbn** [comment]
Moved to new issue tracker.

**Comment by kmbn** [comment]
@joaandrade Since we're using this repo to track harvester issues, we're just reopening this issue. It still needs to be addressed.

**Comment by michellecbox** [comment]
Hi @joaandrade since you are working on another Sentinel issue, can you take a look at this one too? thanks!

**Comment by joaandrade** [comment]
yes @michellecbox. I will look for both issues in the Sentinel harvester.

**Comment by joaandrade** [comment]
Bug fixed in the new branch [sentinel-bug-fixes](https://github.com/NextGeoss/ckanext-nextgeossharvest/tree/sentinel-bug-fixes) with the commit [9cf0458](https://github.com/NextGeoss/ckanext-nextgeossharvest/commit/9cf0458496b5db43d2d5b89df8c1a0a4608f28b0).

The code where the bug was happening only affects the NOA datasets. Now, for the datasets with ingestion dates missing microseconds, the 'Z' is replaced by '.000Z'

**Comment by JGulic** [comment]
@joaandrade please open a pull request for this

**Comment by joaandrade** [comment]
@JGulic done
