### ISSUE TITLE
[GOME-2] Datasets need descriptions

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#44]
Datasets created by the old GOME-2 harvester didn't include descriptions. What should the dataset descriptions be?

**Comment by joaandrade** [comment]
Hi Kevin,

The code you have added to this repository is not the last GOME-2 code. The last GOME-2 code can be found at https://github.com/NextGeoss/ckanext-harvest/blob/sentinel_proba-v_cmems_gome2/ckanext/harvest/harvesters/gome2_harvester.py

Here you will find the dataset descriptions.

**Comment by joaandrade** [comment]
between lines 535 and 553

**Comment by kmbn** [comment]
Thanks—I updated the descriptions.
