### ISSUE TITLE
[GOME-2] Dataset titles are not descriptive

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#45]
The old GOME-2 harvester just repeated the coverage (e.g., `GOME2_O3`) in the `title` field, but that's not very helpful. The new harvester replaces those titles with human readable ones (e.g., `GOME-2 O3`), but that's also not very helpful. What should the dataset titles be?

**Comment by joaandrade** [comment]
Hi Kevin,

The code you have added to this repository is not the last GOME-2 code. The last GOME-2 code can be found at https://github.com/NextGeoss/ckanext-harvest/blob/sentinel_proba-v_cmems_gome2/ckanext/harvest/harvesters/gome2_harvester.py

Here you will find different dataset titles (between lines 535 and 553).

**Comment by kmbn** [comment]
Thanks—I updated the titles.
