### ISSUE TITLE
[GOME-2] Verify that there are new products after 2018-02-17

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#47]
It seems like the GOME-2 program stopped creating new products on 2018-02-16/17 (see https://wdc.dlr.de/wdcservices/wcs.php?&service=wcs&version=1.0.0&request=DescribeCoverage&coverage=GOME2_O3 for example).

Is that the case? Will there be new GOME-2 products, or can we just work with the ones from 2007-01-04 through 2018-02-17?

**Comment by joaandrade** [comment]
DLR and WDC contacted about this topic. Waiting for their feedback.

**Comment by joaandrade** [comment]
The Level 3 production was resumed due to a technical shift to a new raw data distribution scheme.
DLR will resume the production and new data should be available after this weekend (07.05.2018; the production takes some time).

**Comment by kmbn** [comment]
Production has restarted.
