### ISSUE TITLE
[Proba-V] Code re-organization

### ISSUE THREAD

**Issue by joaandrade** [NextGeoss/ckanext-nextgeossharvest#49]
The Proba-V harvester code must be re-organized following a similar approach comparing with the other harvesters:

../harvester/probav.py (class PROBAVHarvester) 
             - main functions: - info, validate_config, gather_stage, fetch_stage

../lib/probav_base.py (class PROBAVBase)
             - rest of the code

**Comment by kmbn** [comment]
Just a reminder: The gather_stage isn't the stage for creating the bulk of the metadata and harvest object extras shouldn't be used for storing metadata that's not essential to the harvest process itself. You can delay creating metadata until the `_parse_content` method that you'll need to write to interact with the NextGEOSS base harvester's `import_stage` flow—you won't have to create it twice.

**Comment by davv-deimos** [comment]
Ongoing in PR #51
