### ISSUE TITLE
[CMEMS] Recover from outages automatically

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#56]
If there's an outage (of the data hub or of the source) and the harvester can't run, it should pick up from where it left off the next time it runs. It should not skip a day or a time period.

Example: The harvester runs without issues from Monday to Wednesday and is up-to-date after it runs on Wednesday. On Thursday there are outages or errors and the harvester cannot complete the harvest. On Friday, the harvester runs again and starts harvesting where it left off, meaning it harvests the missing Thursday products and then harvests Friday as well. It does this without any manual intervention.

**Comment by joaandrade** [comment]
@kmbn I suppose this is done by checking (at the beggining of the job) the date of the last product harvested. Can you post here the typical query to do this operation?

**Comment by joaandrade** [comment]
![workflow](https://user-images.githubusercontent.com/8322111/43253485-fe3028ee-90bc-11e8-917c-15c4e911e588.png)

The workflow I sent via email can recover from outages since it will check the date of the last product. Do you agree @kmbn?

**Comment by joaandrade** [comment]
Probaly this is the piece of code that does the job:

`last_object = Session.query(HarvestObject). \
            filter(HarvestObject.harvest_source_id == self.job.source_id,
                   HarvestObject.import_finished != None). \
            order_by(desc(HarvestObject.import_finished)).limit(1)  # noqa: E711, E501
        if last_object:
            try:
                last_object = last_object[0]
                restart_date = self._get_object_extra(last_object,
                                                      'restart_date', '*')
            except IndexError:
                restart_date = '*'
        else:
            restart_date = '*'
        log.debug('Restart date is {}'.format(restart_date))`

Can you confirm this @kmbn ?

**Comment by kmbn** [comment]
Yes, that's how the ESA harvester determines the last dataset that was imported and which date to use when constructing a new DHuS query at the start of each job.

**Comment by joaandrade** [comment]
The new version of CMEMS harvester is able to restart from where it left. At the beggining of each job, it gets the date of the last dataset harvested and uses it as the new start date.

**Comment by kmbn** [comment]
Thank you!
