### ISSUE TITLE
[GOME2]  Recover from outages automatically

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#57]
If there's an outage (of the data hub or of the source) and the harvester can't run, it should pick up from where it left off the next time it runs. It should not skip a day or a time period.

Example: The harvester runs without issues from Monday to Wednesday and is up-to-date after it runs on Wednesday. On Thursday there are outages or errors and the harvester cannot complete the harvest. On Friday, the harvester runs again and starts harvesting where it left off, meaning it harvests the missing Thursday products and then harvests Friday as well. It does this without any manual intervention.

**Comment by joaandrade** [comment]
@michellecbox, @JGulic, @kmbn 
According to the code implemented in the [gome2_improvements](https://github.com/NextGeoss/ckanext-nextgeossharvest/tree/gome2_improvements) branch, the harvester is able recover from outages. The jobs will start automatically after the first run and the start date will always be the date of the last product harvested.

**Comment by kmbn** [comment]
Resolved by aa367a506b3d793a15b52119fddd759a89b7a213. But note that there's still no solution for  periods where there's not an actual outage but rather a long period where WDC DLR's server _is_ responding but they aren't producing the images. See https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/62#issuecomment-412521729 for more information. That should be addressed in a separate issue, though.

**Comment by joaandrade** [comment]
@kmbn the issue from #62 (comment) will be addressed later. For now, it should be enough to have the harvester running in production right?

If we need to get back in time and harvest a past time interval we have always the [third example](https://github.com/NextGeoss/ckanext-nextgeossharvest/issues/60) of the issue
