### ISSUE TITLE
[PROBAV] Recover from outages automatically

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#58]
If there's an outage (of the data hub or of the source) and the harvester can't run, it should pick up from where it left off the next time it runs. It should not skip a day or a time period.

Example: The harvester runs without issues from Monday to Wednesday and is up-to-date after it runs on Wednesday. On Thursday there are outages or errors and the harvester cannot complete the harvest. On Friday, the harvester runs again and starts harvesting where it left off, meaning it harvests the missing Thursday products and then harvests Friday as well. It does this without any manual intervention.

**Comment by joaandrade** [comment]
The new version of PROBA-V harvester is able to restart from where it left. At the beggining of each job, it gets the date of the last dataset harvested and uses it as the new start date.

**Comment by joaandrade** [comment]
@JGulic @michellecbox  should this proba-v issue be closed? The pull request was already merged

**Comment by joaandrade** [comment]
@JGulic @michellecbox to close this issue

**Comment by JGulic** [comment]
closing this issue
