### ISSUE TITLE
[CMEMS] Harvest from any starting date up to present date and then stay up-to-date automatically

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#59]
Example 1: We start the harvester today and configure it to harvest every product from today onwards. We never have to touch the harvester again and it harvests every new product that becomes available on the source.

Example 2: We start the harvester today and configure it to harvest every product from 1st January onwards. It harvests every product available from 1st January until it catches up with the present state of the source (i.e., if we start it on Monday, it may not manage to harvest all the relevant products until Wednesday). Once it catches up with the present state of the source, if continues harvesting as in example 1. Since there may be many products from the past that need to be harvested, the harvester harvests in stages (e.g., it might harvest only 100 products at a time, but since it harvests more than once a day, or since the number of products it harvests each day is greater than the number of products that are added to the source each day, it eventually catches up with the source).

Example 3: We've been harvesting as in example 1, but now we need to get all the older products that are missing from the data hub as well (e.g., we have everything since 1st June, but we actually need everything since 1st January). If the harvester can meet the requirements in example 2, then it can already meet the requirements of example 3. The solution is just to add a second harvester instance that's configured as in example 2. Once it harvests all the products up to the time that the first harvester started (in this case, 1st June), it will stop adding new products (since the base harvester won't add datasets that already exist). We can stop the second harvester manually. As long the harvester can handle example 1 and example 2, we can use one or more harvesters to harvest all the datasets we need without having to manually update the dates or monitor their progress.

**Comment by joaandrade** [comment]
@kmbn from what I'm seeing in your examples, it would be necessary to have dates in the configuration if we want to start the harvester from a specific date. Do you think the workflow I sent by email can work if we add a starting date in the configuration?

![workflow](https://user-images.githubusercontent.com/8322111/43253383-bbd8ef8a-90bc-11e8-9924-a406395dc1e2.png)

This workflow + a starting date would guarantee that we will be able to harvest everything (even if there is an outage)

**Comment by kmbn** [comment]
Having start dates in the configuration is fine as long as there's a way to run the harvester without having to update the dates once the system is set up.

**Comment by joaandrade** [comment]
According to the code implemented in the cmems_sea_level_product branch, the harvester is able of harvesting from any starting date up to present. The code works for the three examples described.

Each job has a limit of 4 month folders (around 200 datasets).

**Comment by kmbn** [comment]
Thank you!
