### ISSUE TITLE
Move package template snippet and related helper to ckanext-nextgeoss

### ISSUE THREAD

**Issue by kmbn** [NextGeoss/ckanext-nextgeossharvest#64]
They're for the theme, not for the harvesters.

**Comment by joaandrade** [comment]
@kmbn can you solve this issue. I can remove the files from the ckanext-nextgeossharvest repo but the files seem to exist on the ckanext-nextgeoss.

**Comment by kmbn** [comment]
Yes, this issue is for me—sorry, I should have assigned this one to myself when I created it.
On 19. September 2018 at 11:28:33, João Andrade (notifications@github.com) wrote:

@kmbn can you solve this issue. I can remove the files from the ckanext-nextgeossharvest repo but the files seem to exist on the ckanext-nextgeoss.
