### ISSUE TITLE
[SENTINEL] Code-de missing collection name

### ISSUE THREAD

**Issue by JGulic** [NextGeoss/ckanext-nextgeossharvest#95]
### Please describe the expected behaviour
We should be able to collect data from all the collections that we are harvesting from the source.

### Please describe the actual behaviour
The harvester fails when we are trying to collect datasets from CODE-DE.
The error that we are getting in the logs:

`No collection for Sentinel-1 product s5p_nrti_l2__co_____20190315t042331_20190315t042831_07346_01_010202_20190315t051921
ckan_1        | Traceback (most recent call last):
ckan_1        |   File "/usr/bin/paster", line 11, in <module>
ckan_1        |     sys.exit(run())
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
ckan_1        |     invoke(command, command_name, options, args[1:])
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
ckan_1        |     exit_code = runner.run(args)
ckan_1        |   File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
ckan_1        |     result = self.command()
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/commands/harvester.py", line 193, in command
ckan_1        |     fetch_callback(consumer, method, header, body)
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 407, in fetch_callback
ckan_1        |     fetch_and_import_stages(harvester, obj)
ckan_1        |   File "/srv/app/src/ckanext-harvest/ckanext/harvest/queue.py", line 424, in fetch_and_import_stages
ckan_1        |     success_import = harvester.import_stage(obj)
ckan_1        |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 409, in import_stage
ckan_1        |     package = self._create_or_update_dataset(harvest_object, status)
ckan_1        |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/nextgeoss_base.py", line 154, in _create_or_update_dataset
ckan_1        |     parsed_content = self._parse_content(harvest_object.content)
ckan_1        |   File "/usr/lib/python2.7/site-packages/ckanext/nextgeossharvest/lib/esa_base.py", line 238, in _parse_content
ckan_1        |     item['title'] = item['collection_name']
ckan_1        | KeyError: 'collection_name'`

### What steps can be taken to reproduce the issue?
Start the code-de harvester and take a look at the logs

**Comment by joaandrade** [comment]
The updates in the pull request https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/96 should solve the problem

**Comment by JGulic** [comment]
Closing this issue.
Resolved in PR #96
